# Generated by Django 5.0.1 on 2024-01-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=250, null=True)),
                ('content', models.TextField(null=True)),
                ('publish', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
